name: Update Songs Database

on:
  schedule:
    # Run every Saturday at 3:00 AM UTC
    - cron: '0 3 * * 6'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database sync script
        run: python scripts/update_charts.py
      
      - name: Run YouTube ID update script
        run: python scripts/update_videos.py
        env:
          YOUTUBE_API_KEYS: ${{ secrets.YOUTUBE_API_KEYS }}
      # No commit step here anymore: songs.db is published via publish-pages.yml workflow.
      # If you ever need to debug artifacts, you can reintroduce a commit step or upload as an artifact.